stages:
  - before
  - build
  - deploy
  - test

before-job:
  tags:
    - ansible-k8s
  stage: before
  script:
    - echo "before-job1"
    - ansible-playbook -u root -i hosts.ini del-deploy.yml
    - docker rmi registry.my:5000/image:test1
    - curl -u user:l45vegas -s -X DELETE http://172.20.0.2:5000/v2/image/manifests/sha256:4997fa944d2ed794e0cda9402af64c88c577d9ee8fd7b92c3363b7ea85872fce
    - docker login -u user -p l45vegas registry.my:5000

build-job:
  tags:
    - ansible-k8s      
  stage: build
  script:
    - echo "build-job"
    - cd docker-build
    - docker build -t registry.my:5000/image:test1 .
    - docker push registry.my:5000/image:test1

deploy-job:
  tags:
    - ansible-k8s
  stage: deploy
  script:
    - echo "deploy-job"
    - ansible-playbook -u root -i hosts.ini docker-pull.yml
    - ansible-playbook -u root -i hosts.ini test.yml

test-job:
  tags:
    - ansible-k8s       
  stage: test
  script:
    - echo "test-job"
    - curl 192.168.1.250
